python benchmarking/object_erase.py --target "parachute" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/parachute/checkpoints/skill_ratio_0.02_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "english springer" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/english springer/checkpoints/skill_ratio_0.02_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "tench" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/tench/checkpoints/skill_ratio_0.02_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "french horn" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/french horn/checkpoints/skill_ratio_0.02_timesteps_10_threshold0.0.pt" --gpu 1

python benchmarking/object_erase.py --target "parachute" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/parachute/checkpoints/skill_ratio_0.03_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "english springer" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/english springer/checkpoints/skill_ratio_0.03_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "tench" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/tench/checkpoints/skill_ratio_0.03_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "french horn" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/french horn/checkpoints/skill_ratio_0.03_timesteps_10_threshold0.0.pt" --gpu 1

python benchmarking/object_erase.py --target "parachute" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/parachute/checkpoints/skill_ratio_0.04_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "english springer" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/english springer/checkpoints/skill_ratio_0.04_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "tench" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/tench/checkpoints/skill_ratio_0.04_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "french horn" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/french horn/checkpoints/skill_ratio_0.04_timesteps_10_threshold0.0.pt" --gpu 1


python benchmarking/object_erase.py --target "parachute" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/parachute/checkpoints/skill_ratio_0.05_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "english springer" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/english springer/checkpoints/skill_ratio_0.05_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "tench" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/tench/checkpoints/skill_ratio_0.05_timesteps_10_threshold0.0.pt" --gpu 1
python benchmarking/object_erase.py --target "french horn" --hook_module 'unet-ffn-1' --baseline 'concept-prune' --model_id 'runwayml/stable-diffusion-v1-5' --removal_mode erase --ckpt_name "results_FFN-1/results_seed_0/stable-diffusion/runwayml/stable-diffusion-v1-5/french horn/checkpoints/skill_ratio_0.05_timesteps_10_threshold0.0.pt" --gpu 1